sonar.projectKey=unisin-remake-devops
sonar.projectName=Unisin Remake DevOps
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx

sonar.tests=frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info